// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-hAv5r1x8Yj34wlFqbyqjzngFFFLonQY',
    appId: '1:1058714608396:web:d365f97ce938d6f2621f29',
    messagingSenderId: '1058714608396',
    projectId: 'cropcheck-50dc9',
    authDomain: 'cropcheck-50dc9.firebaseapp.com',
    storageBucket: 'cropcheck-50dc9.appspot.com',
    measurementId: 'G-R1Q0K95FNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHKx9rtrjxt_VrPU1xJG2BqM6PnT_ABPo',
    appId: '1:1058714608396:android:0232921873f45a41621f29',
    messagingSenderId: '1058714608396',
    projectId: 'cropcheck-50dc9',
    storageBucket: 'cropcheck-50dc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaYg0Qr3Y2ctdc1f6xUpnV8Us3bVpiHdk',
    appId: '1:1058714608396:ios:c81d4a8a29fda0a9621f29',
    messagingSenderId: '1058714608396',
    projectId: 'cropcheck-50dc9',
    storageBucket: 'cropcheck-50dc9.appspot.com',
    iosBundleId: 'com.afdzn.cropcheckpro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaYg0Qr3Y2ctdc1f6xUpnV8Us3bVpiHdk',
    appId: '1:1058714608396:ios:c81d4a8a29fda0a9621f29',
    messagingSenderId: '1058714608396',
    projectId: 'cropcheck-50dc9',
    storageBucket: 'cropcheck-50dc9.appspot.com',
    iosBundleId: 'com.afdzn.cropcheckpro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-hAv5r1x8Yj34wlFqbyqjzngFFFLonQY',
    appId: '1:1058714608396:web:5b20457f085ef5be621f29',
    messagingSenderId: '1058714608396',
    projectId: 'cropcheck-50dc9',
    authDomain: 'cropcheck-50dc9.firebaseapp.com',
    storageBucket: 'cropcheck-50dc9.appspot.com',
    measurementId: 'G-3MHFQYC0EF',
  );
}
